version: "3"
services:
  redis:
    image: redis
    command: redis-server
    container_name: redis
    environment:
      - discovery.type=single-node
    ports:
      - 6379:6379
    
  modelserver:
    image: apoorv/modelserver
    depends_on:
      - redis
    container_name: modelserver
    
  webserver:
    image: apoorv/webserver
    depends_on:
      - redis
      - modelserver
    ports:
      - 8000:7000